### ISSUE TITLE
hass 111.4 sensor错误

### ISSUE THREAD

**Issue by aktifin** [skyzhishui/custom_components#3]
错误1
Logger: websocket
Source: custom_components/lifesmart/__init__.py:565
First occurred: 下午12:19:55 (2 occurrences)
Last logged: 下午12:24:12

error from callback <function setup.<locals>.on_message at 0x7f75476e1c20>: 'NoneType' object has no attribute 'attributes'

错误2
Logger: homeassistant.core
Source: custom_components/lifesmart/sensor.py:72
First occurred: 下午12:18:40 (1 occurrences)
Last logged: 下午12:18:40

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 326, in _async_write_ha_state
    unit_of_measurement = self.unit_of_measurement
  File "/config/custom_components/lifesmart/sensor.py", line 72, in unit_of_measurement
    return self._unit
AttributeError: 'LifeSmartSensor' object has no attribute '_unit'

不影响使用，但是一直报错

**Comment by skyzhishui** [comment]
应该是官方部分设备有新增的IO idx属性，已优化。
